### ISSUE TITLE
请问怎样部署locally

### ISSUE THREAD

**Issue by chinobing** [aweikalee/tripnote#1]
新年好，请问怎样部署locally，是不是没有设置数据库？ 这个对于旅游规划非常实用。谢谢

![image](https://github.com/aweikalee/tripnote/assets/27722028/e815e3e8-7eb6-4f2b-b7a3-d83909d1cb2b)

**Comment by chinobing** [comment]
![image](https://github.com/aweikalee/tripnote/assets/27722028/fe04e70f-824b-4292-a926-65c4dd4e47b7)

**Comment by aweikalee** [comment]
> 抱歉，没有收到 `issues` 消息提醒，现在才回复。

还有个后端和数据库没有开源（有些敏感信息 没分离出来），
不过我打包了一份剔除敏感信息的代码：
[tripnote.zip](https://github.com/user-attachments/files/15880906/tripnote.zip)

部署前你需要做的是：
1. 修改后端代码中的数据库信息，改为你自己的数据库。
2. 将前端代码 `src/config.ts` 中的 OSS 与 百度地图的配置，替换成你自己的。
3. 将后端代码 `src\oss\oss.service.ts` 中的签名密钥替换为你自己的。
4. 前端调用后端的API地址改为你的服务器地址上（我的项目中使用了反向代理）。


另外这份前端代码，直接使用没什么问题，但不建议修改。
好几年前写的，质量非常糟糕，我自己都懒得改，想重写（但没精力）。
后端原先是 php 写的，后来用 node 重写过。

**Comment by chinobing** [comment]
非常感谢啊，我试试部署哈。
